Module2 task1
htmlacademy-vue/1865155-pizza-1 pull request #2
Opened 2022-06-16 07:42 UTC by slayercool

2022-06-16 11:16 UTC, enotke requested changes

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      value: 0,
В этом компоненте не должно быть состояния. Все данные должны приходить пропсами(за исключением minusDisabled и plusDisabled их можно оставить)

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      minusDisabled: true,
minusDisabled и plusDisabled нужно вычислять в computed свойствах

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +    ingredientId: {},
Нужно как можно подробнее описывать типы

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +        "getItemCount",
лучше назвать update:itemCount это же событие

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      @click="minus"
По идее лучше просто кидать событие $emit('update:itemCount', value + 1)

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +            " pizza__filling--second";
Тоже самое. Классы нужно определять в том месте где они используются, а не тащить их в сторе через всё приложение

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +    clear: function (clear) {
Если избавиться от внутреннего состояния, то этот костыль будет не нужен

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/RadioButton.vue
> +    names: {},
Нужно как можно подробнее описывать типы

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/SelectorItem.vue
> +    ingredientClass: {},
Классы можно передавать в компонент через пропс class

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      this.$refs.childItemCounter[id - 1].plus();
А вот так точно делать не стоит. Рефы используются в редких случаях когда нужно получить доступ к dom элементу например.

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +      this.notdraggable = [...this.notdraggable]; //без этого не перерендерит draggable у списка ингредиентов
Можно использовать this.$set(this.notdraggable, id, boolean). Тогда будет работать. Но опять же notdraggable нужно вычислять исходя из текущего количества ингредиентов, а не хранить это всё в сторе

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderNameSelector.vue
> +        document.getElementsByName("pizza_name")[0].value,
Обычно в Vue не нужно вообще использовать document, ref и всё такое для каких-то базовых вещей. Если не видишь других вариантов, то скорее всего ты что-то делаешь не так

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderNameSelector.vue
> +      @input="sendName"
Тут нужно использовать @input="sendName($event.target.value)" и тогда значение будет передаваться в метод sendName

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderNameSelector.vue
> +    clear: function (clear) {
Опять же костыль из-за потери контроля состояния элементов

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +          :class="filling.className"
Вот тут нужно определять className исходя из количества элементов

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderSizeSelector.vue
> +    RadioButton: () => import("/src/common/components/RadioButton.vue"),
Для импорта нужно использовать алиасы (@)

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/views/Index.vue
> +            размер: {{ myPizza.size }}<br />
Вот такое нужно убирать. Всё должно выглядеть как в макете

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/views/Index.vue
> +            размер: {{ myPizza.size }}<br />
И используй vue devtools для дебага. Гораздо удобнее и функциональнее

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/views/Index.vue
> +        this.myPizza.sauce.value != ""
Нужно установить дефолтные значения для размера и соуса

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/views/Index.vue
> +          this.myPizza.size.id *
нужно умножать на мультипликатор размера а не на id

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +    setDraggable() {
не используется

2022-06-16 11:16 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                :ingredientClass="getIngredientClassName(ingredient.image)"
можно просто :class="getIngredientClassName(ingredient.image)"

2022-06-21 11:37 UTC, slayercool commented on src/frontend/src/common/components/ItemCounter.vue
> +      value: 0,
А разве это будет предпочтительный вариант? Ведь тогда в родительский компонент надо выводить массив значений всех каунтеров. Значит список ингредиентов не получится динамическим, ведь сейчас отрисовка идёт в зависимости от количества ингредиентов в json файле, и если мы вынесем значения каунтеров в родительский, то придётся при добавлении нового ингредиента переписывать код из-за отсутствия значения value в родителе

2022-06-21 11:46 UTC, slayercool commented on src/frontend/src/views/Index.vue
> +            размер: {{ myPizza.size }}<br />
Извиняюсь, забыл убрать. Я vue devtools пользуюсь тоже, но порой он не полностью заменяет отрисовку. Я сталкивался со своими ошибками из-за не полного понимания реактивности и тонкостей работы рендеринга. Вот тогда заметил что в одном месте я вижу происходящие изменения, а в другом нет.

2022-06-21 12:58 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      value: 0,
Так тоже не стоит делать. Желательно отделять статические и динамические структуры. Можно например хранить все в массиве selected ingredients.

2022-06-21 13:00 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      value: 0,
Из-за внутреннего состояния у тебя много лишнего в компонентах. Как говорится первый вариант который приходит в голову как правило самый простой и не самый оптимальный

2022-06-28 12:45 UTC, slayercool commented
Вроде все замечания поправил. Но не смог добиться ререндеринга RadioButton.vue
При отправке пиццы в корзину data в корневом компоненте ставится по дефолту, PizzaView отрисовывает через метод по дефолтным значениям стили, а вот биндинг checked в RadioButton почему-то не видит сброса на дефолт, решения так и не нашёл увы

2022-06-28 22:31 UTC, enotke requested changes

2022-06-28 22:31 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +    myPizzaIngredients: {
Вместо ingredientPrice, ingredientId, myPizzaIngredients нужно передавать только количество конкретного ингредиента. Тогда его не нужно будет постоянно искать

2022-06-28 22:31 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
> +      let index = this.myPizzaIngredients.findIndex(
Вот это всё можно заменить на 
return this.count >= 3

2022-06-28 22:31 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +                @update:itemCount="updateItemCount"
Вместо передачи в компонент кучи данных в компонент можно использовать @update:itemCount="updateItemCount($event, ingredient.id)"

2022-06-28 22:31 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +      if (this.myPizza.name != "" && this.myPizza.ingredients.length != 0) {
Нужно передавать в компонент pizzaName и ingredientsCount, и isDisabled должно быть вычисляемым свойством

2022-06-28 22:31 UTC, enotke commented on src/frontend/src/views/Index.vue
>                @getValueFromBuilder="getValue"
Странное название события. Событие - это какое-то действие. А у тебя действие обрабатывает getValue - который по идее должен что-то возвращать

2022-06-28 22:31 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      this.myPizza.dough.id = 1;
Всё потому что ты передаешь объекты в props, а нужно передавать примитивы.

2022-06-28 23:00 UTC, merged

2022-06-29 09:56 UTC, slayercool commented on src/frontend/src/common/components/ItemCounter.vue
> +      let index = this.myPizzaIngredients.findIndex(
Спасибо! Поубирал все пропсы кидаю только count, а disabled хорошо работает через :disabled="count === 3" соответственно на минус проверка на 0. Меньше кода, проще, лучше

2022-06-29 11:26 UTC, slayercool commented on src/frontend/src/views/Index.vue
> +      this.myPizza.dough.id = 1;
А тут что-то всё равно не получается. Прибиндил в компонент :myPizzaDoughId="myPizza.dough.id" всё равно нет реактивности radiobutton при отправке в корзину

2022-06-29 23:15 UTC, enotke commented on src/frontend/src/views/Index.vue
> +      this.myPizza.dough.id = 1;
А, у тебя в radioButton checked не передается